export const mockData = [
  {
    id: '123456',
    username: 'Gagandeep',
    profession: 'Loving Pet Sitter',
    rating: 5,
    description: 'Dog Sitting, Cat Sitting, pcoket pet and bird care',
    location: 'Toronto, Ontario',
    photo: 'https://res.cloudinary.com/dz8xmxmly/image/upload/v1635438277/cbkxitq6nlngxlcaww5o.png',
    rate: 14,
  },
  {
    id: '123457',
    username: 'Sakshi',
    profession: 'Loving Pet Sitter',
    rating: 5,
    description: 'Professional Dog Trainer',
    location: 'Toronto, Ontario',
    photo: 'https://res.cloudinary.com/dz8xmxmly/image/upload/v1635486859/davt8cpwtni9himahvvy.png',
    rate: 14,
  },
  {
    id: '123454',
    username: 'Shubham Mahajan',
    profession: 'Loving Pet Sitter',
    rating: 5,
    description: 'Dog Sitting',
    location: 'Toronto, Ontario',
    photo: 'https://res.cloudinary.com/dz8xmxmly/image/upload/v1635435593/kgkn4gksyu9xdttnrca7.png',
    rate: 14,
  },
  {
    id: '123498',
    username: 'Gagandeep',
    profession: 'Loving Pet Sitter',
    rating: 5,
    description: 'Dog Sitting, Cat Sitting, pcoket pet and bird care',
    location: 'Toronto, Ontario',
    photo: 'https://res.cloudinary.com/dz8xmxmly/image/upload/v1635438277/cbkxitq6nlngxlcaww5o.png',
    rate: 14,
  },
  {
    id: '12www',
    username: 'Gagandeep',
    profession: 'Loving Pet Sitter',
    rating: 5,
    description: 'Dog Sitting, Cat Sitting, pcoket pet and bird care',
    location: 'Toronto, Ontario',
    photo: 'https://res.cloudinary.com/dz8xmxmly/image/upload/v1635438277/cbkxitq6nlngxlcaww5o.png',
    rate: 14,
  },
  {
    id: '1234ssaaa',
    username: 'Gagandeep',
    profession: 'Loving Pet Sitter',
    rating: 5,
    description: 'Dog Sitting, Cat Sitting, pcoket pet and bird care',
    location: 'Toronto, Ontario',
    photo: 'https://res.cloudinary.com/dz8xmxmly/image/upload/v1635438277/cbkxitq6nlngxlcaww5o.png',
    rate: 14,
  },
];
